version: "3"

services:
  app:
    image: node:latest
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - .:/home/node/app
    command: bash -c "yarn install && yarn start:dev"
